=== eyedeekay/i2p.plugins.firefox/src/i2p.chromium.usability.profile/extensions/jshelter.js/fp_config/schema/groups-schema.json
{
    "$schema":"http://json-schema.org/draft-07/schema",
    "definitions":{
        "group":{
            "type":"object",
            "title":"Group object",
            "description":"Object representing group and its properties.",
            "properties":{
                "name":{
                    "type":"string"
                },
                "description":{
                    "type":"string"
                },
                "criteria":{
                    "$ref":"#/definitions/criteria"
                },
                "groups":{
                    "title":"Subgroups array",
                    "description":"Array of subgroups of defined group.",
                    "type":"array",
                    "items":{
                        "$ref":"#/definitions/group"
                    }
                }
            },
            "required":[
                "name"
            ],
            "additionalProperties":false
        },
        "criteria":{
            "type":"array",
            "title":"Criteria array",
            "description":"Contains criterion objects to define parent group access/weight.",
            "if":{
                "items":[
                    {
                        "$ref":"#/definitions/criterion_access"
                    }
                ]
            },
            "then":{
                "items":{
                    "$ref":"#/definitions/criterion_access"
                }
            },
            "else":{
                "items":{
                    "oneOf":[
                        {
                            "$ref":"#/definitions/criterion_value"
                        },
                        {
                            "$ref":"#/definitions/criterion_percentage"
                        }
                    ]
                }
            }
        },
        "criterion_value":{
            "type":"object",
            "title":"Value criterion",
            "description":"Criterion based on curent weights of direct children. (children = subgroups or wrapped resources)",
            "properties":{
                "value":{
                    "type":"integer",
                    "minimum":1,
                    "maximum":1000
                },
                "weight":{
                    "type":"integer",
                    "minimum":0
                }
            },
            "required":[
                "value",
                "weight"
            ],
            "additionalProperties":false
        },
        "criterion_percentage":{
            "type":"object",
            "title":"Percentage criterion",
            "description":"Criterion based on percentage of currently gained weights (from max. obtainable) of direct children.",
            "properties":{
                "percentage":{
                    "type":"integer",
                    "minimum":0,
                    "maximum":100
                },
                "weight":{
                    "type":"integer",
                    "minimum":0
                }
            },
            "required":[
                "percentage",
                "weight"
            ],
            "additionalProperties":false
        },
        "criterion_access":{
            "type":"object",
            "title":"Access criterion",
            "description":"Criterion based on total number of accesses from direct child resources. (subgroups are ignored)",
            "properties":{
                "access":{
                    "type":"integer",
                    "minimum":1,
                    "maximum":1000
                },
                "weight":{
                    "type":"integer",
                    "minimum":0
                }
            },
            "required":[
                "access",
                "weight"
            ],
            "additionalProperties":false
        },
        "severity_item":{
            "type":"array",
            "title":"Severity item",
            "description":"Each severity item consists of weight number, severity string, and corresponding color.",
            "items":[
                {
                    "num_value": "integer"
                },
                {
                    "text_value": "string"
                },
                {
                    "color": "string",
                    "pattern": "^#(?:[0-9a-fA-F]{3}){1,2}$"
                }
            ],
            "additionalItems": false
        }
    },
    "type":"object",
    "title":"Root group object",
    "description":"Object representing root group and its properties.",
    "properties":{
        "name":{
            "type":"string"
        },
        "description":{
            "type":"string"
        },
        "severity":{
            "type":"array",
            "title":"Severity array",
            "description":"Contains an array of severity items that represent severity thresholds.",
            "items":{
                "$ref":"#/definitions/severity_item"
            }
        },
        "criteria":{
            "$ref":"#/definitions/criteria"
        },
        "groups":{
            "title":"Array of subgroups",
            "description":"Array of subgroups of root group.",
            "type":"array",
            "items":{
                "$ref":"#/definitions/group"
            }
        }
    },
    "required":[
        "name"
    ],
    "additionalProperties":false
}

=== eyedeekay/i2p.plugins.firefox/src/i2p.chromium.usability.profile/extensions/jshelter.js/fp_config/groups-lvl_1.json
{
    "name":"FingerprintingActivity",
    "description":"Definition of fingerprinting behavior by FPD module.",
    "severity": [
        [0, "None", "#3CA519"],
        [1, "Low", "#80B012"],
        [2, "Moderate", "#CD9600"],
        [3, "High", "#E64B19"],
        [5, "Very High", "#C8004B"]
    ],
    "criteria":[
        {
            "value":3,
            "weight":1
        }
    ],
    "groups":[
        {
            "name":"BrowserProperties",
            "description":"Fingerprinting methods based on simple information gathering by accessing certain APIs.",
            "criteria":[
                {
                    "value":7,
                    "weight":1
                },
                {
                    "value":11,
                    "weight":2
                },
                {
                    "value":13,
                    "weight":3
                }
            ],
            "groups":[
                {
                    "name":"NavigatorBasic",
                    "description":"Basic information about browser and system.",
                    "criteria":[
                        {
                            "percentage":35,
                            "weight":1
                        },
                        {
                            "percentage":65,
                            "weight":2
                        }
                    ]
                },
                {
                    "name":"NavigatorHardware",
                    "description":"Hardware information about device.",
                    "criteria":[
                        {
                            "value":1,
                            "weight":1
                        }
                    ]
                },
                {
                    "name":"NavigatorMobile",
                    "description":"Information about features supported by mobile devices.",
                    "criteria":[
                        {
                            "value":1,
                            "weight":1
                        }
                    ]
                },
                {
                    "name":"NavigatorNetwork",
                    "description":"Information about internet connection.",
                    "criteria":[
                        {
                            "value":3,
                            "weight":1
                        }
                    ]
                },
                {
                    "name":"LocalizationInfo",
                    "description":"Localization details and keyboard layout.",
                    "criteria":[
                        {
                            "percentage":50,
                            "weight":1
                        }
                    ]
                },
                {
                    "name":"PermissionsInfo",
                    "description":"Querying different permissions through API.",
                    "criteria":[
                        {
                            "percentage":100,
                            "weight":1
                        }
                    ]
                },
                {
                    "name":"AudioInfo",
                    "description":"AudioContext configuration parameters.",
                    "criteria":[
                        {
                            "percentage":40,
                            "weight":1
                        }
                    ]
                },
                {
                    "name":"ScreenInfo",
                    "description":"Information about screen and its properties.",
                    "criteria":[
                        {
                            "value":5,
                            "weight":1
                        }
                    ]
                },
                {
                    "name":"WindowInfo",
                    "description":"Information about screen from root Window object.",
                    "criteria":[
                        {
                            "value":3,
                            "weight":1
                        }
                    ]
                },
                {
                    "name":"StorageInfo",
                    "description":"Availability of WebStorage technology.",
                    "criteria":[
                        {
                            "percentage":60,
                            "weight":1
                        }
                    ]
                },
                {
                    "name":"NavigatorFlags",
                    "description":"Binary browser settings.",
                    "criteria":[
                        {
                            "percentage":100,
                            "weight":1
                        }
                    ]
                },
                {
                    "name":"TimeInfo",
                    "description":"Information about exact time values.",
                    "criteria":[
                        {
                            "access":10,
                            "weight":1
                        }
                    ]
                },
                {
                    "name":"WebGLInfo",
                    "description":"Information from WebGL/WebGL2 interface.",
                    "criteria":[
                        {
                            "percentage":50,
                            "weight":1
                        }
                    ]
                }
            ]
        },
        {
            "name":"AlgorithmicMethods",
            "description":"Fingerprinting methods based on specific procedures, calculations or processing.",
            "criteria":[
                {
                    "value":1,
                    "weight":2
                },
                {
                    "value":2,
                    "weight":3
                }
            ],
            "groups":[
                {
                    "name":"FontsEnumFingerprint",
                    "description":"System fonts enumeration techniques.",
                    "criteria":[
                        {
                            "percentage":50,
                            "weight":1
                        }
                    ],
                    "groups":[
                        {
                            "name":"JSFontEnum",
                            "criteria":[
                                {
                                    "percentage":100,
                                    "weight":1
                                }
                            ],
                            "groups":[
                                {
                                    "name":"JSFontEnumStepOne"
                                },
                                {
                                    "name":"JSFontEnumStepTwo",
                                    "criteria":[
                                        {
                                            "access":15,
                                            "weight":1
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            "name":"CanvasFontEnum",
                            "criteria":[
                                {
                                    "percentage":100,
                                    "weight":1
                                }
                            ],
                            "groups":[
                                {
                                    "name":"CanvasFontEnumStepOne"
                                },
                                {
                                    "name":"CanvasFontEnumStepTwo"
                                }
                            ]
                        }
                    ]
                },
                {
                    "name":"CanvasFingerprint",
                    "description":"Extraction of rendered image from 2D canvas.",
                    "criteria":[
                        {
                            "percentage":100,
                            "weight":1
                        }
                    ],
                    "groups":[
                        {
                            "name":"CanvasFingerprintStepOne",
                            "criteria":[
                                {
                                    "percentage":50,
                                    "weight":1
                                }
                            ]
                        },
                        {
                            "name":"CanvasFingerprintStepTwo",
                            "criteria":[
                                {
                                    "access":2,
                                    "weight":1
                                }
                            ]
                        },
                        {
                            "name":"CanvasFingerprintStepThree"
                        }
                    ]
                },
                {
                    "name":"WebGLFingerprint",
                    "description":"Extraction of rendered image from WebGL canvas.",
                    "criteria":[
                        {
                            "percentage":50,
                            "weight":1
                        }
                    ],
                    "groups":[
                        {
                            "name":"WebGL1Fingerprint",
                            "criteria":[
                                {
                                    "percentage":100,
                                    "weight":1
                                }
